services:
  # O Traefik continua rodando, mas não vai mais gerenciar o znuny-app por enquanto
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik-proxy"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/acme.json:/letsencrypt/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - znuny-net
    restart: always

  # Landing page continua normal
  landing-page:
    image: nginx:alpine
    container_name: landing-page
    volumes:
      - "./landing-page:/usr/share/nginx/html:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landingpage.rule=Host(`portal.grupoga230.com.br`)"
      - "traefik.http.routers.landingpage.entrypoints=websecure"
      - "traefik.http.routers.landingpage.tls.certresolver=letsencrypt"
      - "traefik.http.services.landingpage.loadbalancer.server.port=80"
    networks:
      - znuny-net
    restart: always

  # --- MUDANÇAS IMPORTANTES NO ZNUNY-APP ---
  znuny-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ZNUNY_VERSION=7.1
    container_name: znuny-app
    depends_on:
      db:
        condition: service_healthy
    # Expõe a porta 80 do container na porta 8088 do seu servidor
    ports:
      - "8088:80"
    volumes:
      - znuny_app_data:/opt/znuny/var
      # Mapeia o Config.pm para garantir a conexão com o BD
      - ./Config.pm:/opt/znuny/Kernel/Config.pm:ro
    # A seção 'labels' foi REMOVIDA para este teste
    networks:
      - znuny-net
    restart: always

  # SERVIÇO DO BANCO (com healthcheck)
  db:
    image: mysql:8.0
    container_name: znuny-mysql-db
    command:
      - '--default-authentication-plugin=mysql_native_password'
      - '--innodb_log_file_size=256M'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=Birosca1967!
      - MYSQL_DATABASE=znuny_db
      - MYSQL_USER=znuny_user
      - MYSQL_PASSWORD=Birosca1967!
    volumes:
      - znuny_db_data:/var/lib/mysql
    networks:
      - znuny-net
    restart: always

volumes:
  znuny_db_data:
  znuny_app_data:

networks:
  znuny-net: