services:
  # SERVIÇO TRAEFIK (sem mudanças)
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik-proxy"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/acme.json:/letsencrypt/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - znuny-net
    restart: always

  # LANDING PAGE (sem mudanças)
  landing-page:
    image: nginx:alpine
    container_name: landing-page
    volumes:
      - "./landing-page:/usr/share/nginx/html:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landingpage.rule=Host(`portal.grupoga230.com.br`)"
      - "traefik.http.routers.landingpage.entrypoints=websecure"
      - "traefik.http.routers.landingpage.tls.certresolver=letsencrypt"
      - "traefik.http.services.landingpage.loadbalancer.server.port=80"
    networks:
      - znuny-net
    restart: always

  # SERVIÇO ZNUNY (depends_on atualizado)
  znuny-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ZNUNY_VERSION=7.1
    container_name: znuny-app
    depends_on:
      db:
        condition: service_healthy # <-- MUDANÇA AQUI
    volumes:
      - znuny_app_data:/opt/znuny/var
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.znuny.rule=Host(`portal.grupoga230.com.br`) && PathPrefix(`/servicedesk`)"
      - "traefik.http.routers.znuny.entrypoints=websecure"
      - "traefik.http.routers.znuny.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.strip-servicedesk.stripprefix.prefixes=/servicedesk"
      - "traefik.http.routers.znuny.middlewares=strip-servicedesk@docker"
      - "traefik.http.services.znuny.loadbalancer.server.port=80"
    networks:
      - znuny-net
    restart: always

  # SERVIÇO DO BANCO (healthcheck adicionado)
  db:
    image: mysql:8.0
    container_name: znuny-mysql-db
    command:
      - '--default-authentication-plugin=mysql_native_password'
      - '--innodb_log_file_size=256M'
    healthcheck: # <-- MUDANÇA AQUI
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=Birosca1967!
      - MYSQL_DATABASE=znuny_db
      - MYSQL_USER=znuny_user
      - MYSQL_PASSWORD=Birosca1967!
    volumes:
      - znuny_db_data:/var/lib/mysql
    networks:
      - znuny-net
    restart: always

volumes:
  znuny_db_data:
  znuny_app_data:

networks:
  znuny-net: