# traefik/traefik.yml
log:
  level: DEBUG

# Habilita a API/Dashboard do Traefik
api:
  dashboard: true
  insecure: true # Permite acesso na porta 8080 (ótimo para debug)

# Define os pontos de entrada para o tráfego web
entryPoints:
  web:
    address: ":80"
    # Configura um redirecionamento global de HTTP para HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Habilita o Docker como provedor de configuração
providers:
  docker:
    exposedByDefault: false

# Configura o resolvedor de certificados da Let's Encrypt
certificatesResolvers:
  letsencrypt:
    acme:
      email: "marcelo.barreto@grupoga230.com.br"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web